warrant-dev/warrant

pkg/authz/check/handlers.go, tests/authz-wildcard.json, tests/authz.json
This PR updates the authorize endpoint to match the API endpoint available in Warrant Cloud so SDKs can continue to work as expected.
=> Update authorize endpoint from v1 to v2

cmd/warrant/main.go, pkg/service/auth.go, pkg/service/router.go
This PR allows for a custom auth middleware to be used in place of the default auth middleware. When initializing the router, a function of type `AuthMiddlewareFunc` is accepted to replace the default middleware.
=> Allow custom auth middleware when initializing router

pkg/authz/feature/mysql.go, pkg/authz/feature/postgres.go, pkg/authz/permission/mysql.go, pkg/authz/permission/postgres.go, pkg/authz/pricingtier/mysql.go, pkg/authz/pricingtier/postgres.go, pkg/authz/role/mysql.go, pkg/authz/role/postgres.go
In every Warrant resource's repository `Create` method, we have an update clause that executes in the case of a duplicate record based on a matching unique key column (e.g. `featureId`, `permissionId`, etc). This means that a record for a resource of that type with the same unique key already exists but is deleted (i.e. `deletedAt` is not `NULL`). Currently, for the `permission`, `role`, `feature`, and `pricing-tier` resources, we also update the unique key column in the update clause. Although this doesn't have any functional impact, we don't need to do this, so this PR removes the unique key column from the update clause for each of those resources.
=> Remove update of unique key column from repository Create method of permission, role, feature, and pricing-tier resources

pkg/event/mysql.go, pkg/event/postgres.go, pkg/event/spec.go
For each resource event / access event, we generate a UUID. This UUID is typically generated by the underlying database when a new event record is inserted. Since each database has its own way of generating UUIDs (or lack of UUID support), it's better to generate a UUID in the code. This PR updates the events service to generate a UUID for each event before the event is persisted.
=> Generate event UUIDs in code rather than relying on the underlying eventstore database

go.mod, go.sum, pkg/config/config.go
We currently use [viper](https://github.com/spf13/viper) to read the `warrant.yaml` config file and/or read env vars and assign them into our `Config` struct. In order to get the latter working, we've already had to write quite a bit of custom code. Now we've noticed that [viper does not correctly return a `viper.ConfigFileNotFoundError`](https://github.com/spf13/viper/issues/1491) when the configured yaml config file is not found, so the library doesn't really provide much value. As a result, I've decided to remove it and instead implement our own yaml file parsing + env var parsing. This PR adds that.
=> Remove usage of github.com/spf13/viper for reading in config from environment variables and read them in manually instead

cmd/warrant/Makefile, pkg/database/sqlite-stub.go, pkg/database/sqlite.go
The `go-sqlite3` lib requires CGO which we don't have enabled and will require proper cross-compiling to get working, and likely a different docker base image. For now, given we don't anticipate sqlite usage in prod, don't compile it via a build tag. You can still build with sqlite locally with `make dev` and run all apirunner tests.
In the future we can consider replacing with a pure-Go sqlite impl.
=> Add build tag for sqlite + stubbed sqlite db

cmd/warrant/main.go, pkg/authz/check/service.go, pkg/authz/feature/service.go, pkg/authz/objecttype/service.go, pkg/authz/permission/service.go, pkg/authz/pricingtier/service.go, pkg/authz/role/service.go, pkg/authz/tenant/service.go, pkg/authz/user/service.go, pkg/authz/warrant/service.go, pkg/config/config.go, pkg/event/mysql.go, pkg/event/postgres.go, pkg/event/service.go, tests/zz-events.json
Events can now be configured to run synchronously. A `synchronizeEvents` boolean can now be passed as part of the `eventstore` config to specify that events be run synchronously.
```yaml
eventstore:
synchronizeEvents: true
```
Or via env var:
```bash
EVENTSTORE_SYNCHRONIZEEVENTS=true
```
=> Allow events to be configured to run synchronously and add initial test suite for events

pkg/authz/check/service.go, pkg/authz/feature/service.go, pkg/authz/object/handlers.go, pkg/authz/object/service.go, pkg/authz/objecttype/service.go, pkg/authz/permission/service.go, pkg/authz/pricingtier/service.go, pkg/authz/role/service.go, pkg/authz/tenant/service.go, pkg/authz/user/service.go, pkg/authz/warrant/service.go, pkg/context/service.go, pkg/event/service.go
This PR exports the repository and services in `XService` types, in order to allow them to be extended by allowing new types to embed the service and override the repository or service struct fields.
=> Export service fields

pkg/event/spec.go, pkg/event/sqlite.go
This makes the event timestamps consistent with the precision used within the core warrant tables:
`2023-04-21 17:50:18.226966+00:00`
=> Set event createdAt to Now() from within query

pkg/authz/feature/spec.go, pkg/authz/permission/spec.go, pkg/authz/pricingtier/spec.go, pkg/authz/role/spec.go
Context is a warrant concept that shouldn't be a field on the role, permission, pricingTier or feature spec types. This PR removes the context field from the mentioned spec definitions.
=> Remove context from non-warrant specs

pkg/authz/feature/spec.go, pkg/authz/permission/spec.go, pkg/authz/pricingtier/spec.go, pkg/authz/role/spec.go, pkg/authz/tenant/service.go, pkg/authz/tenant/spec.go, pkg/authz/user/service.go, pkg/authz/user/spec.go, pkg/authz/warrant/spec.go, pkg/service/json.go, tests/warrants.json, tests/zz-events.json
This PR make updates to accept colons as a valid character in object ids for warrants. Subsequently, user and tenant id validations have been updated to also accept colons as valid. The `StringToWarrantSpec` and `StringToSubjectSpec` methods have been updated to handle scenarios where there is a colon in the object id.
Addresses #106
=> Allow colons in object id

pkg/authz/feature/service.go, pkg/authz/permission/service.go, pkg/authz/pricingtier/service.go, pkg/authz/role/service.go, pkg/authz/tenant/service.go, pkg/authz/user/service.go, pkg/authz/warrant/service.go
In this PR, event calls made in service methods containing a transaction are moved to be within the transaction. This allows the transaction to fail if the event call fails if event calls are being made synchronously.
=> Track events within transactions

pkg/database/sql.go
This PR updates `WithinTransaction` to use `BeginTxx` from the `sqlx` package in order to pass in the request context when running a transaction . This allows `sqlx` to automatically handle DB rollbacks when there are any SQL errors, such as a context cancellation.
=> Use BeginTxx when running a transaction to pass context in

pkg/authz/feature/handlers.go, pkg/authz/object/handlers.go, pkg/authz/objecttype/handlers.go, pkg/authz/permission/handlers.go, pkg/authz/pricingtier/handlers.go, pkg/authz/role/handlers.go, pkg/authz/tenant/handlers.go, pkg/authz/user/handlers.go
When fetching query param values using `mux.Vars`, the value returned is already unescaped. By calling `QueryUnescape` on the returned value, we unescape the value twice which can return unexpected values.
=> Update query param parsing

pkg/authz/user/spec.go, tests/users-crud.json
Some users want to use the `email` field on the User resource to store free-form values (like a username or other user-friendly identifiers), so this PR removes validation on the `UserSpec`'s `Email` field to allow for free-form (non-email) values to be used as well.
=> Remove email validation on UserSpec.Email field to allow free-form values

pkg/authz/check/service.go, pkg/authz/warrant/mysql.go, pkg/authz/warrant/postgres.go, pkg/authz/warrant/repository.go, pkg/authz/warrant/sqlite.go, tests/authz-wildcard.json, tests/authz-wildcard2.json, tests/zz-events.json
Currently, **wildcards warrants are required to resolve to at least one existing warrant with an explicit `objectId` specified**. This approach was initially favored to provide additional protections / integrity (especially when dealing with context). However, in scenarios where wildcard warrants indirectly reference warrants having an explicit `objectId`, the wildcard warrant doesn't have a warrant (directly related to itself) to resolve to, so any dependent access checks incorrectly return an unauthorized response.
This PR does two things:
(1) Fixes the issue described above by allowing wildcard `objectId`s in warrants to resolve to **any** `objectId` rather than looking to resolve them to an existing `objectId` (with matching context). This approach no longer provides protections / …
=> Handle wildcard objectIds in access checks

pkg/authz/check/service.go, tests/authz.json, tests/zz-events.json
Currently, the authorize endpoint doesn't return the debug info in some scenarios. This PR ensures that the debug info is always returned when requested. The PR also adds some additional test scenarios covering the usage of [indirect warrants](https://docs.warrant.dev/concepts/warrants/#indirect-warrants).
=> Return debug info in all authorized scenarios + add authz tests for indirect warrants

pkg/authz/check/service.go, tests/authz.json
This PR updates the Check method and its related methods to include the warrant that leads to an Authorized result for a warrant check.
Consider the following scenario:
- User `1` is a member of role `admin`
- Role `admin` is a member of permission `edit-items`
If we do the following check: Is user `1` a member of permission `edit-items`? We would only get the following warrant returned as part of the decision path: `user 1 is a member of role admin`.
With the proposed changes, the decision path would now include the complete path:
```
- User `1` is a member of role `admin`
- Role `admin` is a member of permission `edit-items`
```
=> Include matching warrant in decisionPath for authz checks

cmd/warrant/main.go, pkg/authz/feature/repository.go, pkg/authz/object/repository.go, pkg/authz/objecttype/repository.go, pkg/authz/permission/repository.go, pkg/authz/pricingtier/repository.go, pkg/authz/role/repository.go, pkg/authz/tenant/repository.go, pkg/authz/user/repository.go, pkg/authz/warrant/repository.go, pkg/authz/warrant/spec.go, pkg/database/sqlite-stub.go, pkg/database/sqlite.go, pkg/event/repository.go, pkg/service/auth.go
This PR updates all usages of `fmt.Errorf` to use `errors.New` (for new errors) or `errors.Wrap` (for instances where an already existing error is being bubbled up) instead. `errors.New` saves the stack trace at the current point which is useful for debugging and `errors.Wrap` ensures that we don't swallow a legitimate error. 
N/A
=> Update usages of `fmt.Errorf` to `errors.New` where applicable

pkg/authz/warrant/service.go
This PR removes the unused `Get` method from the `WarrantService`
N/A
=> Remove unused `Get` method from warrant service

pkg/authz/check/service.go, pkg/database/mysql.go, pkg/database/postgres.go, pkg/database/sql.go, pkg/database/sqlite.go, pkg/event/service.go, pkg/service/middleware.go, pkg/service/router.go, pkg/stats/stats.go
- Use hlog.FromContext() logger wherever possible (to preserve context in logs)
- Create a request-level stats obj that can be logged for debugging:
```
1:16PM INF ACCESS clientIp=[ duration=6.689708 method=POST numQueries=4 protocol=HTTP/1.1 requestId=ci52001hct9nfn1tpic0 requestStats={"numQueries":4,"queries":[{"duration":0.000042,"queryType":"sql.read.Select","store":"127.0.0.1/warrantOSS"},{"duration":0.000042,"queryType":"sql.read.GetContext","store":"127.0.0.1/warrantOSS"},{"duration":0.000042,"queryType":"sql.read.Select","store":"127.0.0.1/warrantOSS"},{"duration":0.000042,"queryType":"sql.write.NamedExec","store":"127.0.0.1/warrantOSSEvents"}]} size=39 statusCode=200 uri=/v2/authorize userAgent=Go-http-client/1.1
```
N/A
=> Use contextual loggers + add reqStats object

pkg/authz/warrant/warrant.go, pkg/authz/warrant/warrant_test.go, pkg/database/mysql.go, pkg/database/postgres.go, pkg/database/sqlite.go, tests/authz-policy.json
This PR adds back support for providing `context` when creating/deleting a warrant in order to keep those endpoints backwards compatible even with the addition of warrant policies. If `context` is passed when creating a warrant, the endpoint will automatically convert the context into a policy which is the `&&` (AND) of the key value pairs passed in the `context`. The same logic will apply when `context` is passed to the delete warrant endpoint.
N/A
=> Make the create and delete warrant endpoints backward compatible with context

pkg/config/config.go, pkg/database/database.go, pkg/database/mysql.go, pkg/database/postgres.go, pkg/database/sql.go, pkg/database/sqlite.go
- Allow for configuration of 'reader' sql dbs in addition to primary 'writer'
- Expose simple api for repos/services to make use of read-only conns
https://github.com/warrant-dev/warrant/issues/162
=> Add support for sql 'reader' dbs

pkg/authz/object/list.go, pkg/authz/objecttype/list.go
This PR fixes typos in the `object` and `objecttype` packages' list middleware
N/A
=> Fix typo in `object` and `objecttype` package list middleware error messages

pkg/authz/wookie/service.go, pkg/database/database.go, pkg/database/sql.go, pkg/event/service.go
- Change event service read methods for access and resource events to use the db's consistentRead method if the syncEvents config is 'false'
=> Change event svc read methods to useConsistentRead if syncEvents is false

pkg/event/service.go
This PR exports the `SynchronizeEvents` and `CreateEventContext` fields of `EventService` for use by external packages.
=> Export event service fields

cmd/warrant/main.go, pkg/authz/wookie/service.go, pkg/config/config.go
- Make warrant tokens (wookies) enabled/disabled configurable. If disabled, no wookies will be generated or considered in read ops. If enabled, wookies are considered in reads and updated wookies are returned in API responses.
=> Add a config toggle for enabling/disabling warrant tokens (wookies)

pkg/authz/warrant/mysql.go, pkg/authz/warrant/postgres.go, pkg/authz/warrant/repository.go, pkg/authz/warrant/service.go, pkg/authz/warrant/sqlite.go, tests/authz-policy.json
This PR updates the warrant service's `DeleteRelatedWarrants` method to track `access_revoked` events when cascade deleting warrants related to a deleted object.
N/A
=> Track events for cascade warrant deletes on object deletion

migrations/datastore/mysql/README.md, pkg/config/config.go, pkg/database/mysql.go
This PR adds support for DSN (Data Source Name) to the MySQL configuration, which allows users to provide a string describing a connection to a datasource. This also allows users to specify any [available parameters](https://github.com/go-sql-driver/mysql#dsn-data-source-name) when providing a DSN, i.e. `root:@tcp(127.0.0.1:3306)/warrant?allowAllFiles=true&collation=latin1_swedish_ci`.
=> Add DSN field to mysql config

cmd/warrant/main.go, pkg/database/mysql.go
This PR fixes the configuration setup to correctly handle cases when either a `DSN` or `ReaderDSN` is provided. When initializing the DB, an additional check is added to see if a `DSN` is provided in order to start initializing the DB connection. For initializing the reader DB, the check is also updated to see if a `ReaderDSN` has been provided to determine whether to connect to a reader instance.
=> Correctly handle DSN config

.github/workflows/golangci-lint.yml
- Set fetch-depth to 2. This should prevent all previous lint errors from showing up as errors in ci.
=> Set golangci-lint job fetch depth to 2 commits

pkg/authz/warrant/warrant.go, tests/authz-policy.json
This PR updates warrant creation to return a more useful error response when the client attempt to create a warrant with an invalid policy (syntax error or otherwise).
N/A
=> Return invalid parameter error with useful error message when client attempts to create a warrant with an invalid policy

pkg/authz/warrant/mysql.go, pkg/authz/warrant/postgres.go, pkg/authz/warrant/sqlite.go
This PR updates the list warrants database queries to check for a nil subject in the filter options to avoid a nil reference error when filters are passed without a subject.
=> Check warrant filters for nil subject

.golangci.yaml, pkg/authz/check/service.go
- Limit Check service concurrency to 1 by default, create separate CheckParallel() for callers that want to run in parallel
=> Limit Check service concurrency to 1 by default

pkg/authz/feature/service.go, pkg/authz/feature/spec.go, pkg/authz/object/handlers.go, pkg/authz/object/service.go, pkg/authz/object/spec.go, pkg/authz/permission/service.go, pkg/authz/permission/spec.go, pkg/authz/pricingtier/service.go, pkg/authz/pricingtier/spec.go, pkg/authz/role/service.go, pkg/authz/role/spec.go, pkg/authz/tenant/service.go, pkg/authz/tenant/spec.go, pkg/authz/user/service.go, pkg/authz/user/spec.go, tests/objects-crud.json
With this change, it is no longer required to pass an `objectId` when creating an object. If one is passed, it will be used as the `objectId` for the created object (no change here), but if an `objectId` is not passed, the service will generate a v4 uuid to use as the `objectId` for the newly created object.
N/A
=> Make the `objectId` field optional on object, and generate an `objectId` for objects created without one

pkg/authz/warrant/policy.go, pkg/authz/warrant/policy_test.go
- Add convenience methods to support `and-ing`, `or-ing` and `not-ing` policies.
=> Support and, or, not on policies

pkg/authz/objecttype/service.go, tests/authz.json
This PR updates the object type map lookup to return a record not found error if the requested object type is not found in the map.
N/A
=> Return `RecordNotFoundError` from object type map

pkg/authz/object/service.go, pkg/authz/warrant/service.go, tests/tenants-crud.json, tests/users-crud.json, tests/warrants-crud.json, tests/zz-events.json
This PR updates the object service's `Create` method to update the existing object (instead of returning a `DuplicateRecordError`) in the scenario that an already existing object is passed.
N/A
=> Update the object service `Create` method to update existing objects

pkg/authz/objecttype/handlers.go, pkg/authz/objecttype/service.go, pkg/authz/warrant/handlers.go, pkg/authz/warrant/service.go, pkg/authz/wookie/service.go, pkg/wookie/wookie.go
This PR updates the `objecttype` and `warrant` Service interfaces to have the write methods return a wookie token in addition to the existing return values. This allows the wookie token to optionally be returned in the response. `WithNewWookie` is also created as a wrapper around `WithinTransaction`, where a new wookie is created, a transaction is started (or continued), and the new wookie is passed to the callback function.
=> Wookie interface updates

pkg/authz/wookie/middleware.go, pkg/service/router.go, pkg/wookie/wookie.go
This PR renames the existing wookie middleware and a new wookie middleware (`WookieMiddleware`) which fetches the wookie token and sets it in the request context.
The current wookie middlename is renamed from `WookieMiddleware` to `WarrantTokenMiddleware` and simply sets the `Warrant-Token` header value in context. This allows queries to be handled appropriately by either the reader or writer instance. The new wookie middleware `WookieMiddleware` can be applied to applicable endpoints and fetches/parses the token and sets it in context.
=> Add wookie middleware

tests/authz-policy.json, tests/objects-crud.json, tests/warrants-crud.json
This PR adds tests for duplicate record creation for objects, object types, and warrants. Instead of erroring out, these endpoints will update the `createdAt` and `updatedAt` of the existing record.
=> Add tests for duplicate record creation

pkg/object/spec.go, tests/objects-crud.json
This PR adds validation to the `objectType` field of `CreateObjectSpec` to ensure valid object types when creating objects.
=> Add objectType validation to CreateObjectSpec

pkg/object/feature/service.go, pkg/object/handlers.go, pkg/object/permission/service.go, pkg/object/pricingtier/service.go, pkg/object/role/service.go, pkg/object/service.go, pkg/object/tenant/service.go, pkg/object/user/service.go
Updates the object service's delete method to return a wookie because it cascade deletes warrants related to the object.
N/A
=> Return wookie from object delete method

pkg/object/feature/spec.go, pkg/object/permission/spec.go, pkg/object/pricingtier/spec.go, pkg/object/role/spec.go, pkg/object/tenant/spec.go, pkg/object/user/spec.go
This PR adds `XSpecFromQueryResult` methods, which can convert a query result into either a `FeatureSpec`, `PricingTierSpec`, `PermissionSpec`, `RoleSpec`, `TenantSpec`, or `UserSpec`.
=> Add spec from query result methods

pkg/authz/objecttype/mysql.go, pkg/authz/objecttype/postgres.go, pkg/authz/objecttype/sqlite.go, pkg/authz/warrant/mysql.go, pkg/authz/warrant/postgres.go, pkg/authz/warrant/sqlite.go, pkg/object/mysql.go, pkg/object/postgres.go, pkg/object/sqlite.go, tests/objects-crud.json
If a duplicate key is encountered during an INSERT query, the `createdAt` is always updated regardless if the record is currently deleted or not. This PR updates the create queries for the `object`, `objectType` and `warrant` tables to only update the `createdAt` when the record is currently deleted.
=> Update create queries to only createdAt when record is deleted

pkg/authz/warrant/service.go
This PR updates the automatic object creation when creating a warrant to ignore the subject if the objectId is a wildcard.
=> Ignore wildcard subject objectIds when creating warrant objects

.golangci.yaml, pkg/authz/query/service.go, tests/v2/query.json
When selecting a set of subjects using a query like `select member of type user for permission:A`, the query API returns results of types other than just `user`. This PR updates the query API to only return results of the specified subject type(s) if specified.
N/A
=> Filter query results by the specified subject type(s) when selecting subjects

pkg/authz/warrant/list.go, pkg/object/spec.go, pkg/service/list.go
=> Update `SortOrder` type alias and make `ListParams` JSON serializable

.github/workflows/go.yaml
=> Pin version of `golangci-lint` to `v1.55` (include patches) in GitHub workflow

pkg/authz/query/resultset.go, pkg/authz/query/service.go, pkg/authz/query/spec.go, tests/v1/query.json
This PR adds a new `Relation` attribute to the `QueryResult` type. This new attribute is useful for internal use of query to help determine the relation of the result when a wildcard is used in the query string (e.g. `select * of type user for document:X`).
N/A
=> Add a `Relation` attribute to `QueryResult` (for internal use)

pkg/authz/query/resultset.go, pkg/authz/query/service.go, tests/v2/query.json
This PR updates the query endpoint to return the relation as part of the cursor. It also updates the logic used to determine if a result is implicit or not.
N/A
=> Update query cursor to include relation + fix implicit result logic

pkg/authz/query/resultset.go
Optimize the `ResultSet` struct's `Intersect` method to iterate over the shorter of the two sets being intersected.
N/A
=> Optimize `ResultSet.Intersect` method

pkg/authz/query/resultset.go
Fix `ResultSet` `Intersect` method to correctly intersect query results by looping over the shorter of the two sets
N/A
=> Fix `ResultSet` `Intersect` method

pkg/authz/query/handlers.go, pkg/authz/query/parser.go, pkg/authz/query/resultset.go, pkg/authz/query/service.go, pkg/authz/query/spec.go, tests/v2/query-policy.json
This PR adds policy support to the query endpoint. The endpoint now accepts an optional `context` parameter which can contain a URL encoded JSON object containing various context to respect during the evaluation of the query.
Closes #314
=> Add policy support to query endpoint

pkg/authz/objecttype/spec.go, tests/v1/object-types-crud.json, tests/v2/object-types-crud.json
Allows creation of object-types with an empty relations block. For example:
```json
{
"type": "user",
"relations": {}
}
```
Closes #317
=> Allow creation of object-types with an empty relations block

cmd/warrant/main.go, pkg/authz/objecttype/model.go, pkg/authz/warrant/handlers.go, pkg/authz/warrant/list.go, pkg/authz/warrant/model.go, pkg/authz/warrant/mysql.go, pkg/authz/warrant/postgres.go, pkg/authz/warrant/sqlite.go, pkg/config/config.go, pkg/database/sql.go, tests/v1/warrants-list.json, tests/v2/warrants-list.json
This PR updates `DatastoreConfig` to be an interface that requires implementation of `GetMySQL()`, `GetPostgres()`, and `GetSQLite()` methods.
N/A
=> Make `DatastoreConfig` an interface

pkg/authz/query/parser.go
Add word boundary at beginning and end of all query language keywords in query lexer. This prevents the lexer from incorrectly matching user-defined object-types and resources as query language keywords which can result in the query API incorrectly reporting syntax errors.
Closes #330
=> Add word boundary at beginning and end of all query language keywords in query lexer
