warrant-dev/warrant

- migrations/datastore/mysql/README.md
- migrations/datastore/postgres/README.md
- pkg/config/config.go
- pkg/service/auth.go
- pkg/service/router.go
This PR adds basic API key middleware that checks the Authorization header against an API key stored in an environment variable.
> Add basic api key middleware

- pkg/database/postgres.go
This PR updates the postgres connection logic to build the connection string with `net/url`'s `UserPassword` method which will escape any special characters in username/password. The `go-sql-driver/mysql` already [escapes special characters in the connection string automatically](https://github.com/go-sql-driver/mysql#password), so this change isn't required for mysql.
> Escape username and password in Postgres connection string

- pkg/authz/check/handlers.go
- pkg/authz/feature/handlers.go
- pkg/authz/object/handlers.go
- pkg/authz/objecttype/handlers.go
- pkg/authz/permission/handlers.go
- pkg/authz/pricingtier/handlers.go
- pkg/authz/role/handlers.go
- pkg/authz/tenant/handlers.go
- pkg/authz/user/handlers.go
- pkg/authz/warrant/handlers.go
This PR exports all endpoint handlers which allows for them to be reused for other routes or configured for different use cases.
> Export handlers for routes to be configured

- cmd/warrant/main.go
Update the postgres migration version numbers to the latest available migrations for postgres.
> Update the latest postgres migration versions

- pkg/database/sql.go
- pkg/service/router.go
- pkg/stats/stats.go
- Consolidate RequestStats logic
- Expose method to add 'breadcrumbs' to RequestStats queries
> Consolidate RequestStats logic

- .github/workflows/go.yaml
- .github/workflows/mysql.yaml
- .github/workflows/postgres.yaml
- .github/workflows/release.yaml
- .github/workflows/sqlite.yaml
- Update to latest versions of go setup and goreleaser GH actions
> Update go env and goreleaser actions

- .github/workflows/go.yaml
- .github/workflows/golangci-lint.yml
- .golangci.yaml
- pkg/service/auth.go
- pkg/service/json.go
- Use golangci-lint to lint all go files (more exhaustive than just running go vet + staticcheck)
> Add golangci-lint

- .golangci.yaml
- Use new-from-rev HEAD~1 instead of 'new' (diff against last commit)
> Change golangci-lint new-from-rev HEAD~1

- pkg/authz/role/service.go
This PR updates the `ListRoles` service method in the `role` package to return any error from the repository method.
> Return error from list roles method

- cmd/warrant/main.go
- pkg/authz/check/service.go
- pkg/stats/stats.go
- Add ability for check service users to provide a ctx setup method.
> Use clean ctx for checks

- .github/workflows/release.yaml
- .goreleaser.yaml
- Add arm64 docker img generation to goreleaser config
> Create docker images for arm64 linux

- tests/warrant-list.json
- tests/zz-events.json
> Remove remaining objects from tests

- .github/workflows/release.yaml
- cmd/warrant/main.go
- pkg/authz/check/service.go
- pkg/config/config.go
- pkg/database/mysql.go
- pkg/database/postgres.go
- pkg/database/sql.go
- pkg/database/sqlite.go
- pkg/event/service.go
- pkg/service/auth.go
- pkg/service/json.go
- pkg/service/middleware.go
- pkg/service/router.go
- Standardize log msgs with prefixes for easier debugging
> Standardize log msgs

- pkg/authz/query/service.go
> Use the `objecttype.Service` interface in the query service

- pkg/authz/query/service.go
- pkg/authz/warrant/service.go
- pkg/object/feature/service.go
- pkg/object/permission/service.go
- pkg/object/pricingtier/service.go
- pkg/object/role/service.go
- pkg/object/service.go
- pkg/object/tenant/service.go
- pkg/object/user/service.go
This PR creates Service interfaces for the `warrant` and `object` packages.
> Create warrant and object service interfaces

- pkg/authz/warrant/service.go
> Return err instead of nil in error case

- pkg/authz/wookie/middleware.go
- pkg/authz/wookie/service.go
- pkg/wookie/token.go
- pkg/wookie/wookie.go
Consolidates `ClientPassedWookieCtxKey` and `ServerCreatedWookieCtxKey` into one context key for ease of on writes.
N/A
> Consolidate `ClientPassedWookieCtxKey` and `ServerCreatedWookieCtxKey`

- pkg/wookie/wookie.go
Unexport wookie context key types and update `WithNewWookie` to use separate context key to check if it was already invoked.
N/A
> Updates to `WithNewWookie`

- pkg/authz/wookie/service.go
> Update `WithNewWookie` to use separate context key to check if it was already invoked

- pkg/authz/objecttype/service.go
- pkg/authz/warrant/mysql.go
- pkg/authz/warrant/postgres.go
- pkg/authz/warrant/repository.go
- pkg/authz/warrant/service.go
- pkg/authz/warrant/sqlite.go
- pkg/authz/wookie/middleware.go
- pkg/authz/wookie/service.go
- pkg/wookie/wookie.go
- tests/authz-policy.json
- tests/warrants-crud.json
Cleans up unused `DeletedById` method in warrant repository + minor updates to wookie package methods for ease of use and correctness.
N/A
> Minor updates to wookie handling

- pkg/authz/check/service.go
- pkg/authz/objecttype/service.go
- pkg/authz/query/service.go
- pkg/service/middleware.go
> Remove ObjectTypeMap from svcs

- pkg/authz/warrant/list.go
- pkg/authz/wookie/middleware.go
> Change filterParams String() and return http 4xx if client-passed wookie is invalid

- pkg/authz/check/service.go
- pkg/authz/check/spec.go
- tests/authz-policy.json
- tests/authz-wildcard.json
- tests/authz-wildcard2.json
- tests/authz.json
- tests/pricing-tiers-and-features.json
Adds an `isImplicit` boolean flag to the check result/response indicating that a warrant check resolved to true via an implicit warrant match.
N/A
> Add `isImplicit` boolean flag to check result

- pkg/authz/query/parser.go
- pkg/authz/query/spec.go
- Add a String() method to Query
> Add String() to Query

- .github/workflows/mysql.yaml
- .github/workflows/postgres.yaml
- .github/workflows/sqlite.yaml
- development.md
> Add apirunner testname arg

- pkg/authz/check/service.go
- pkg/event/service.go
> Recover and handle errs in check and event goroutines

- pkg/service/errors.go
> Export `GenericError` type

- pkg/authz/objecttype/mysql.go
- pkg/authz/objecttype/postgres.go
- pkg/authz/objecttype/sqlite.go
- pkg/authz/warrant/mysql.go
- pkg/authz/warrant/postgres.go
- pkg/authz/warrant/service.go
- pkg/authz/warrant/sqlite.go
- pkg/database/sql.go
- pkg/event/mysql.go
- pkg/event/postgres.go
- pkg/event/repository.go
- pkg/event/sqlite.go
- pkg/object/model.go
- pkg/object/mysql.go
- pkg/object/postgres.go
- pkg/object/sqlite.go
- pkg/service/json.go
- pkg/stats/stats.go
> Cleanup usage of `switch err.(type)`

- pkg/authz/check/handlers.go
- pkg/authz/objecttype/handlers.go
- pkg/authz/warrant/handlers.go
- pkg/object/feature/handlers.go
- pkg/object/handlers.go
- pkg/object/permission/handlers.go
- pkg/object/pricingtier/handlers.go
- pkg/object/role/handlers.go
- pkg/object/tenant/handlers.go
- pkg/object/user/handlers.go
- pkg/service/json.go
Add context to json parsing methods so the error logs can include the request context.
> Add context to json parsing methods

- README.md
Update development section of README to include links to both development and deployment docs.
N/A
> Update development section of README

- pkg/stats/stats.go
- `RequestStats` can be read/written to by multiple go routines. Guard read/writes with a mutex.
> Guard RequestStats reads/writes with mutex

- pkg/object/role/list.go
> Add parsing to support sorting roles list by createdAt

- pkg/service/json.go
- Log any errors encountered when writing json response payloads to stream
> Log any errors encountered when writing json response

- tests/v1/authz-policy.json
- tests/v1/authz-wildcard.json
- tests/v1/authz-wildcard2.json
- tests/v1/authz.json
- tests/v1/pricing-tiers-and-features.json
- tests/v2/authz-policy.json
- tests/v2/authz-wildcard.json
- tests/v2/authz-wildcard2.json
- tests/v2/authz.json
> Add Warrant-Token latest to all check reqs in tests

- pkg/authz/check/service.go
- pkg/authz/query/service.go
> Increase maximum number of adjacent/neighbor warrants query and expand can evaluate

- pkg/authz/check/handlers.go
- tests/v2/authz.json
> Add check handler

- pkg/wookie/wookie.go
> Remove Get/Set wookie ctx methods

- README.md
> Make minor updates to the wording in the README

- tests/v1/query.json
- tests/v2/query.json
> Add Warrant-Token latest to query tests

- README.md
> Reorganize the README + add sections on limitations and enterprise options

- .gitignore
- pkg/authz/objecttype/mysql.go
- pkg/authz/objecttype/postgres.go
- pkg/authz/objecttype/repository.go
- pkg/authz/objecttype/sqlite.go
> Remove unused ListAll() from objecttype repository

- .github/workflows/go.yaml
- .github/workflows/mysql.yaml
- .github/workflows/postgres.yaml
- .github/workflows/release.yaml
- .github/workflows/sqlite.yaml
- go.mod
> Use go 1.22

- pkg/service/json.go
> Add url validate case to return InvalidParameterError

- pkg/authz/check/service.go
- pkg/authz/query/handlers.go
- pkg/authz/query/parser.go
- pkg/authz/query/resultset.go
- pkg/authz/query/service.go
- pkg/authz/query/spec.go
- pkg/authz/warrant/handlers.go
- pkg/authz/warrant/list.go
- pkg/authz/warrant/mysql.go
- pkg/authz/warrant/postgres.go
- pkg/authz/warrant/sqlite.go
- pkg/service/list.go
- tests/v1/query.json
- tests/v1/warrants-list.json
- tests/v2/query.json
- tests/v2/warrants-list.json
This PR rewrites query execution so that it breaks down the query into sub-problems better + finds all matching results across all types of queries.
N/A
> Rewrite + Improve Query Execution

- pkg/authz/query/resultset.go
> Update ResultSet to only add new records to list if they don't already exist

- README.md
Update main image in `README.md`
N/A
> Update main image in `README.md`

- pkg/authz/query/list.go
- pkg/authz/query/resultset.go
- pkg/authz/query/service.go
- pkg/authz/query/spec.go
- tests/v1/query.json
- tests/v2/query.json
This PR updates the `QueryResult` type's new `Relation` attribute to be returned in the JSON API response. It also updates the query endpoint's sort functions to account for this new relation attribute.
N/A
> Return new `relation` field in `QueryResult` JSON response

- tests/v2/query-policy.json
> Add `'Warrant-Token: latest'` header to query calls in `query-policy.json` test suite

- pkg/authz/objecttype/spec.go
- tests/v1/object-types-crud.json
- tests/v2/object-types-crud.json
Allow object-type updates with an empty relations block
N/A
> Allow object-type updates with an empty relations block

- CONTRIBUTING.md
- SECURITY.md
> Update security email

- CODE_OF_CONDUCT.md
- README.md
> Update Readme + links
